"use client"

import Link from "next/link"
import { useState, type FormEvent, type ReactNode } from "react"
import { ArrowRight, Check, CircleHelp, FileText, LockKeyhole, Menu, Network, ShieldCheck, Sparkles, X, type LucideIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useLanguage } from "@/lib/i18n/language-context"
import { LanguageSwitcher } from "@/components/language-switcher"
import { localizedPath } from "@/lib/i18n/routing"

const icons: LucideIcon[] = [Network, FileText, ShieldCheck, Sparkles, CircleHelp, LockKeyhole]

type PublicPageKey = "home" | "funktionen" | "kontakt" | "preise" | "registrierung" | "login"

const copy = {
  de: {
    nav: { home: "Startseite", features: "Plattformfunktionen", contact: "Kontakt", pricing: "Preise", register: "Registrieren", login: "Anmelden", menu: "Menü öffnen", close: "Menü schließen" },
    home: { eyebrow: "DEINE FINANZIELLE ÜBERSICHT AN EINEM ORT", title: "Verstehe deine Finanzen. Triff bessere Entscheidungen.", description: "Strukturiere wichtige finanzielle und administrative Informationen an einem Ort und erkenne, welche Themen deine Aufmerksamkeit benötigen.", primary: "Profil erstellen", secondary: "Funktionen entdecken", introTitle: "Eine klare Verbindung zwischen deinen Informationen und deinen nächsten Schritten", intro: "FinanzBG hilft dir, Informationen zu ordnen, Zusammenhänge zu verstehen und mögliche nächste Schritte bewusst zu prüfen.", features: "Alles Wichtige für deine Finanzen – strukturiert an einem Ort", how: "So funktioniert die Plattform", cta: "Starte mit einer klareren Übersicht über deine finanzielle Situation", ctaText: "Erstelle dein Profil und organisiere wichtige Informationen an einem Ort.", start: "Jetzt starten" },
    features: { eyebrow: "PLATTFORMAUFBAU", title: "Alles Wichtige für deine Finanzen – strukturiert an einem Ort", description: "Die Plattform verbindet wichtige Informationen zu deinem Profil, deinen Dokumenten, Verträgen, Ausgaben, Fristen und möglichen Optimierungsbereichen in einer verständlichen Übersicht." },
    contact: { eyebrow: "KONTAKT", title: "Wir helfen dir gerne weiter", description: "Hast du eine Frage zur Plattform oder zu unseren Funktionen? Sende uns eine Nachricht. Wir melden uns so bald wie möglich bei dir.", name: "Name", email: "E-Mail-Adresse", subject: "Betreff", message: "Nachricht", send: "Nachricht senden", pending: "Das Kontaktformular wird derzeit mit dem E-Mail-Dienst verbunden. Deine Nachricht wurde noch nicht versendet.", back: "Zurück zur Startseite" },
    pricing: { eyebrow: "PREISE", title: "Ein klarer Einstieg in deine finanzielle Übersicht", description: "Die verfügbaren Funktionen und Preise werden transparent dargestellt, sobald die jeweiligen Produktbereiche verbindlich festgelegt sind.", pending: "Preis folgt", contact: "Kontakt aufnehmen", note: "Die konkreten Preise und der verfügbare Funktionsumfang werden vor dem jeweiligen Start transparent ausgewiesen." },
    auth: { registerEyebrow: "REGISTRIERUNG", registerTitle: "Erstelle dein Profil", registerDescription: "Beginne damit, deine finanzielle und administrative Übersicht strukturiert aufzubauen.", loginEyebrow: "ANMELDUNG", loginTitle: "Willkommen zurück", loginDescription: "Melde dich an, um deine persönliche Übersicht zu öffnen.", first: "Vorname", last: "Nachname", email: "E-Mail-Adresse", password: "Passwort", confirm: "Passwort bestätigen", accept: "Ich akzeptiere die Datenschutzbestimmungen und die Allgemeinen Geschäftsbedingungen.", create: "Konto erstellen", signIn: "Anmelden", already: "Du hast bereits ein Konto?", noAccount: "Noch kein Konto?", register: "Jetzt registrieren", forgot: "Passwort vergessen?", pendingRegister: "Die Registrierung wird mit dem Authentifizierungsdienst verbunden. Es wurde noch kein Konto erstellt.", pendingLogin: "Die Anmeldung wird mit dem Authentifizierungsdienst verbunden." },
    cards: [{ title: "Finanzprofil", desc: "Eine gemeinsame Grundlage für deine finanzielle und administrative Übersicht." }, { title: "Dokumente und Verträge", desc: "Organisiere wichtige Dokumente und behalte Bedingungen und Fristen im Blick." }, { title: "Ausgaben und Verpflichtungen", desc: "Erkenne, wofür du regelmäßig zahlst und welche Bereiche Aufmerksamkeit verdienen." }, { title: "Mögliche Chancen", desc: "Erkenne potenzielle Optimierungsbereiche auf Grundlage der vorhandenen Informationen." }, { title: "Risiken und Fristen", desc: "Behalte wichtige Fristen, fehlende Dokumente und Veränderungen im Blick." }, { title: "Verständliche Erklärungen", desc: "Erhalte klare Erklärungen zu komplexen finanziellen und administrativen Themen." }],
    steps: [{ title: "Informationen hinzufügen", desc: "Füge relevante Informationen zu deiner persönlichen Situation hinzu." }, { title: "Übersicht erhalten", desc: "Ordne deine Informationen in einer zentralen Übersicht." }, { title: "Chancen und Risiken verstehen", desc: "Erkenne, welche Themen möglicherweise wichtig sind." }, { title: "Nächsten Schritt auswählen", desc: "Entscheide selbst, welche Handlung als Nächstes sinnvoll ist." }],
    plans: [{ title: "Basis", subtitle: "Für den Einstieg", items: ["Finanzprofil vorbereiten", "Wichtige Informationen strukturieren", "Grundlegende Übersicht"] }, { title: "Plattform", subtitle: "Für eine umfassendere Übersicht", items: ["Dokumente und Verträge organisieren", "Fristen und Aufgaben im Blick behalten", "Weitere Funktionen nach Verfügbarkeit"] }, { title: "Individuelle Lösung", subtitle: "Für besondere Anforderungen", items: ["Weitere Informationen auf Anfrage", "Persönliche Anforderungen besprechen"] }],
    footer: { privacy: "Datenschutz", imprint: "Impressum", terms: "Allgemeine Geschäftsbedingungen" }
  },
  bg: {
    nav: { home: "Начало", features: "Функции на платформата", contact: "Контакт", pricing: "Цени", register: "Регистрация", login: "Вход", menu: "Отвори менюто", close: "Затвори менюто" },
    home: { eyebrow: "ТВОЯТА ФИНАНСОВА ИНФОРМАЦИЯ НА ЕДНО МЯСТО", title: "Разбери финансите си. Вземай по-добри решения.", description: "Организирай важната финансова и административна информация на едно място и виж кои теми изискват твоето внимание.", primary: "Създай профил", secondary: "Разгледай функциите", introTitle: "Ясна връзка между информацията и следващите ти действия", intro: "FinanzBG помага да подредиш информацията, да разбереш връзките и съзнателно да прецениш възможните следващи стъпки.", features: "Всичко важно за твоите финанси — организирано на едно място", how: "Как работи платформата", cta: "Започни с по-ясна картина на финансовата си ситуация", ctaText: "Създай профил и организирай важната информация на едно място.", start: "Започни сега" },
    features: { eyebrow: "СТРУКТУРА НА ПЛАТФОРМАТА", title: "Всичко важно за твоите финанси — организирано на едно място", description: "Платформата свързва информацията за твоя профил, документи, договори, разходи, срокове и възможни области за оптимизация в разбираем преглед." },
    contact: { eyebrow: "КОНТАКТ", title: "С удоволствие ще ти помогнем", description: "Имаш въпрос относно платформата или нейните функции? Изпрати ни съобщение. Ще ти отговорим възможно най-скоро.", name: "Име", email: "Имейл адрес", subject: "Тема", message: "Съобщение", send: "Изпрати съобщение", pending: "Контактната форма в момента се свързва с имейл услуга. Съобщението ти все още не е изпратено.", back: "Назад към началната страница" },
    pricing: { eyebrow: "ЦЕНИ", title: "Ясен старт към по-добър финансов преглед", description: "Наличните функции и цени ще бъдат представени прозрачно, когато съответните продуктови области бъдат окончателно определени.", pending: "Цената предстои", contact: "Свържи се с нас", note: "Конкретните цени и наличният обхват ще бъдат обявени прозрачно преди старта на съответната услуга." },
    auth: { registerEyebrow: "РЕГИСТРАЦИЯ", registerTitle: "Създай своя профил", registerDescription: "Започни да изграждаш структурирана финансова и административна картина.", loginEyebrow: "ВХОД", loginTitle: "Добре дошъл отново", loginDescription: "Влез, за да отвориш личния си преглед.", first: "Име", last: "Фамилия", email: "Имейл адрес", password: "Парола", confirm: "Потвърди паролата", accept: "Приемам политиката за поверителност и общите условия.", create: "Създай профил", signIn: "Вход", already: "Вече имаш профил?", noAccount: "Все още нямаш профил?", register: "Регистрирай се сега", forgot: "Забравена парола?", pendingRegister: "Регистрацията ще бъде свързана с auth услугата. Все още не е създаден профил.", pendingLogin: "Входът ще бъде свързан с auth услугата." },
    cards: [{ title: "Финансов профил", desc: "Една обща основа за твоята финансова и административна картина." }, { title: "Документи и договори", desc: "Организирай важните документи и следи условията и сроковете." }, { title: "Разходи и задължения", desc: "Виж за какво плащаш редовно и кои области изискват внимание." }, { title: "Възможности", desc: "Откривай потенциални области за оптимизация на база наличната информация." }, { title: "Рискове и срокове", desc: "Следи важни срокове, липсващи документи и промени." }, { title: "Разбираеми обяснения", desc: "Получавай ясни обяснения на сложни финансови и административни теми." }],
    steps: [{ title: "Добавяш информация", desc: "Добавяш релевантна информация за своята ситуация." }, { title: "Получаваш преглед", desc: "Подреждаш информацията в централен преглед." }, { title: "Разбираш възможности и рискове", desc: "Виждаш кои теми може да са важни." }, { title: "Избираш следваща стъпка", desc: "Сам решаваш кое действие е подходящо след това." }],
    plans: [{ title: "База", subtitle: "За начало", items: ["Подготовка на финансов профил", "Структуриране на важна информация", "Основен преглед"] }, { title: "Платформа", subtitle: "За по-пълен преглед", items: ["Организиране на документи и договори", "Следене на срокове и задачи", "Допълнителни функции според наличността"] }, { title: "Индивидуално решение", subtitle: "За специални изисквания", items: ["Допълнителна информация при запитване", "Обсъждане на индивидуални изисквания"] }],
    footer: { privacy: "Поверителност", imprint: "Импресум", terms: "Общи условия" }
  }
} as const

function GoldCableBackground() {
  return <div aria-hidden="true" className="gold-cable-background"><svg viewBox="0 0 1440 1200" preserveAspectRatio="none"><path d="M-80 180 C 260 40, 380 420, 680 260 S 1080 20, 1520 220" /><path d="M-120 760 C 220 520, 360 920, 720 690 S 1100 430, 1540 620" /><path d="M220 -80 C 340 180, 160 360, 430 560 S 780 800, 650 1280" /><path d="M1110 -60 C 980 220, 1290 300, 1080 560 S 900 940, 1220 1280" /></svg></div>
}

function PublicHeader() {
  const { locale } = useLanguage()
  const c = copy[locale].nav
  const [open, setOpen] = useState(false)
  const links = [{ href: "/", label: c.home }, { href: "/funktionen", label: c.features }, { href: "/kontakt", label: c.contact }, { href: "/preise", label: c.pricing }]
  return <header className="public-header"><div className="public-container flex h-20 items-center justify-between gap-4"><Link href={localizedPath("/", locale)} className="brand-mark"><span>Finanz<span>BG</span></span><small>VZG PLATTFORM</small></Link><nav className="hidden items-center gap-1 lg:flex" aria-label="Primary navigation">{links.map((link) => <Link key={link.href} href={localizedPath(link.href, locale)} className="public-nav-link">{link.label}</Link>)}</nav><div className="flex items-center gap-2"><LanguageSwitcher className="public-language" /><div className="hidden items-center gap-2 md:flex"><Button asChild variant="ghost" size="sm"><Link href={localizedPath("/login", locale)}>{c.login}</Link></Button><Button asChild size="sm" className="gold-button"><Link href={localizedPath("/registrierung", locale)}>{c.register}</Link></Button></div><button type="button" className="mobile-menu-button lg:hidden" aria-label={open ? c.close : c.menu} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></div>{open && <nav className="mobile-public-nav lg:hidden" aria-label="Mobile navigation">{[...links, { href: "/preise", label: c.pricing }, { href: "/registrierung", label: c.register }, { href: "/login", label: c.login }].map((link, index) => <Link key={`${link.href}-${index}`} href={localizedPath(link.href, locale)} onClick={() => setOpen(false)}>{link.label}</Link>)}</nav>}</header>
}

function PublicFooter() {
  const { locale } = useLanguage(); const c = copy[locale]; const n = c.nav
  return <footer className="public-footer"><div className="public-container grid gap-10 py-12 md:grid-cols-[1fr_auto]"><div><div className="brand-mark"><span>Finanz<span>BG</span></span><small>VZG PLATTFORM</small></div><p className="mt-4 max-w-sm text-sm text-slate-400">{c.home.intro}</p></div><nav className="grid grid-cols-2 gap-x-10 gap-y-3 text-sm text-slate-300"><Link href={localizedPath("/funktionen", locale)}>{n.features}</Link><Link href={localizedPath("/preise", locale)}>{n.pricing}</Link><Link href={localizedPath("/kontakt", locale)}>{n.contact}</Link><Link href={localizedPath("/login", locale)}>{n.login}</Link><Link href={localizedPath("/registrierung", locale)}>{n.register}</Link><span className="text-slate-500">{c.footer.privacy}</span><span className="text-slate-500">{c.footer.imprint}</span><span className="text-slate-500">{c.footer.terms}</span></nav></div><div className="public-container border-t border-white/10 py-5 text-xs text-slate-500">© {new Date().getFullYear()} FinanzBG · VZG Plattform</div></footer>
}

function Shell({ children }: { children: ReactNode }) { return <div className="public-site"><GoldCableBackground /><PublicHeader /><main className="relative z-10">{children}</main><PublicFooter /></div> }

function Intro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="public-container public-page-intro"><p className="public-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="public-lead">{description}</p></div> }

function Cards({ compact = false }: { compact?: boolean }) { const { locale } = useLanguage(); const c = copy[locale]; return <div className={`grid gap-4 sm:grid-cols-2 ${compact ? "lg:grid-cols-3" : "lg:grid-cols-3"}`}>{c.cards.map((item, index) => { const Icon = icons[index]; return <article key={item.title} className="public-card"><span className="public-icon"><Icon /></span><h3>{item.title}</h3><p>{item.desc}</p></article> })}</div> }

function HomePage() { const { locale } = useLanguage(); const c = copy[locale]; return <Shell><section className="public-hero"><div className="public-container relative z-10 grid items-center gap-12 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-28"><div><p className="public-eyebrow">{c.home.eyebrow}</p><h1>{c.home.title}</h1><p className="public-lead">{c.home.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="gold-button h-12 rounded-full px-7"><Link href={localizedPath("/registrierung", locale)}>{c.home.primary}<ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="h-12 rounded-full border-blue-300/30 bg-white/5 px-7 text-white hover:bg-white/10"><Link href={localizedPath("/funktionen", locale)}>{c.home.secondary}</Link></Button></div></div><div className="hero-system-card"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><Network className="mx-auto size-16 text-amber-300" /><p className="mt-5 text-center text-sm text-slate-300">{c.home.introTitle}</p><div className="mt-6 grid grid-cols-2 gap-3 text-xs text-slate-400"><span>Data</span><span>Understanding</span><span>Analysis</span><span>Action</span></div></div></div></section><section className="public-section"><div className="public-container"><div className="max-w-2xl"><p className="public-eyebrow">{c.home.features}</p><h2>{c.home.introTitle}</h2><p className="public-lead">{c.home.intro}</p></div><div className="mt-10"><Cards compact /></div></div></section><section className="public-section border-y border-white/10 bg-white/[.03]"><div className="public-container"><p className="public-eyebrow">{c.home.how}</p><div className="mt-8 grid gap-4 md:grid-cols-4">{c.steps.map((step, i) => <div key={step.title} className="step-card"><span>{String(i + 1).padStart(2, "0")}</span><h3>{step.title}</h3><p>{step.desc}</p></div>)}</div></div></section><section className="public-cta"><div className="public-container flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><h2>{c.home.cta}</h2><p>{c.home.ctaText}</p></div><Button asChild size="lg" className="gold-button rounded-full"><Link href={localizedPath("/registrierung", locale)}>{c.home.start}<ArrowRight /></Link></Button></div></section></Shell> }

function FeaturesPage() { const { locale } = useLanguage(); const c = copy[locale]; return <Shell><Intro {...c.features} /><section className="public-section pt-0"><div className="public-container"><Cards /><div className="mt-20"><p className="public-eyebrow">{c.home.how}</p><div className="mt-8 grid gap-4 md:grid-cols-4">{c.steps.map((step, i) => <div className="step-card" key={step.title}><span>{i + 1}</span><h3>{step.title}</h3><p>{step.desc}</p></div>)}</div></div></div></section><section className="public-cta"><div className="public-container flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><h2>{c.home.cta}</h2><Button asChild className="gold-button rounded-full"><Link href={localizedPath("/registrierung", locale)}>{c.home.primary}<ArrowRight /></Link></Button></div></section></Shell> }

function ContactPage() { const { locale } = useLanguage(); const c = copy[locale].contact; const [submitted, setSubmitted] = useState(false); function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSubmitted(true) } return <Shell><Intro {...c} /><section className="public-section pt-0"><div className="public-container grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div className="public-card self-start"><CircleHelp className="size-8 text-amber-300" /><h2 className="mt-5">{c.title}</h2><p className="mt-3 text-slate-300">{c.description}</p></div><form className="public-form" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="contact-name">{c.name}</Label><Input id="contact-name" required /></div><div><Label htmlFor="contact-email">{c.email}</Label><Input id="contact-email" type="email" required /></div></div><div><Label htmlFor="contact-subject">{c.subject}</Label><Input id="contact-subject" required /></div><div><Label htmlFor="contact-message">{c.message}</Label><textarea id="contact-message" required rows={6} /></div>{submitted && <p className="form-notice" role="status">{c.pending}</p>}<Button className="gold-button" type="submit">{c.send}<ArrowRight /></Button></form></div></section></Shell> }

function PricingPage() {
  const { locale } = useLanguage()
  const c = copy[locale]
  const planCards = c.plans.map((plan, index) => (
    <article key={plan.title} className={`public-card flex flex-col ${index === 1 ? "pricing-featured" : ""}`}>
      <p className="public-eyebrow">{plan.title}</p>
      <h2>{plan.subtitle}</h2>
      <p className="pricing-pending">{c.pricing.pending}</p>
      <ul className="mt-6 space-y-3 text-sm text-slate-300">{plan.items.map((item) => <li key={item} className="flex gap-2"><Check className="size-4 shrink-0 text-amber-300" />{item}</li>)}</ul>
      <div className="mt-auto pt-8">
        <Button asChild variant="outline" className="w-full"><Link href={localizedPath(index === 2 ? "/kontakt" : "/registrierung", locale)}>{index === 2 ? c.pricing.contact : c.nav.register}</Link></Button>
      </div>
    </article>
  ))
  return <Shell><Intro {...c.pricing} /><section className="public-section pt-0"><div className="public-container"><div className="grid gap-5 lg:grid-cols-3">{planCards}</div><p className="mx-auto mt-8 max-w-2xl text-center text-sm text-slate-400">{c.pricing.note}</p></div></section></Shell>
}

function AuthPage({ mode }: { mode: "login" | "register" }) { const { locale } = useLanguage(); const c = copy[locale].auth; const register = mode === "register"; const [submitted, setSubmitted] = useState(false); return <Shell><div className="public-container py-16 lg:py-24"><div className="mx-auto max-w-xl"><div className="public-card auth-card"><p className="public-eyebrow">{register ? c.registerEyebrow : c.loginEyebrow}</p><h1>{register ? c.registerTitle : c.loginTitle}</h1><p className="public-lead">{register ? c.registerDescription : c.loginDescription}</p><form className="public-form mt-8" onSubmit={(e) => { e.preventDefault(); setSubmitted(true) }}>{register && <div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="first">{c.first}</Label><Input id="first" required /></div><div><Label htmlFor="last">{c.last}</Label><Input id="last" required /></div></div>}<div><Label htmlFor="auth-email">{c.email}</Label><Input id="auth-email" type="email" required /></div><div><Label htmlFor="auth-password">{c.password}</Label><Input id="auth-password" type="password" required minLength={8} /></div>{register && <><div><Label htmlFor="confirm">{c.confirm}</Label><Input id="confirm" type="password" required minLength={8} /></div><label className="flex gap-3 text-sm text-slate-300"><input type="checkbox" required />{c.accept}</label></>}{submitted && <p className="form-notice" role="status">{register ? c.pendingRegister : c.pendingLogin}</p>}<Button className="gold-button w-full" type="submit">{register ? c.create : c.signIn}<ArrowRight /></Button></form>{!register && <Link className="mt-5 block text-center text-sm text-amber-300 hover:text-amber-200" href="#">{c.forgot}</Link>}<p className="mt-8 text-center text-sm text-slate-400">{register ? c.already : c.noAccount} <Link className="font-semibold text-amber-300" href={localizedPath(register ? "/login" : "/registrierung", locale)}>{register ? c.signIn : c.register}</Link></p></div></div></div></Shell> }

export function PublicSite({ page }: { page: PublicPageKey }) { if (page === "home") return <HomePage />; if (page === "funktionen") return <FeaturesPage />; if (page === "kontakt") return <ContactPage />; if (page === "preise") return <PricingPage />; return <AuthPage mode={page === "login" ? "login" : "register"} /> }
