'use client'

import { usePathname, useRouter } from 'next/navigation'
import { useState } from 'react'
import { createClient } from '@/lib/office/supabase/client'
import { authCopy } from '@/lib/office/auth-copy'
import { CaseWorkspace } from '@/components/office/case-workspace'
import { BookOpen, Check, ChevronDown, CircleHelp, FileCheck2, FileText, Globe2, Inbox, Languages, LayoutDashboard, LifeBuoy, Menu, MessageCircle, MoreHorizontal, Paperclip, Plus, ShieldCheck, Sparkles, Upload, WifiOff } from 'lucide-react'

const locales = ['bg', 'de', 'ru', 'pl', 'sr', 'ro'] as const
type Locale = (typeof locales)[number]

const localeNames: Record<Locale, string> = { bg: 'Български', de: 'Deutsch', ru: 'Русский', pl: 'Polski', sr: 'Srpski', ro: 'Română' }
const copy: Record<Locale, any> = {
  de: { greeting:'Guten Morgen, ', subtitle:'Wobei können wir heute helfen?', uploadTitle:'Dokument oder Anliegen hochladen', uploadText:'PDF, Bild oder Text hier ablegen', browse:'Datei auswählen', supported:'Unterstützt: PDF, JPG, PNG · Max. 10 MB', recent:'Zuletzt bearbeitet', allCases:'Alle Vorgänge', newCase:'Neuen Vorgang starten', clarify:'Rückfrage erforderlich', draft:'Entwurf bereit', processing:'Wird verarbeitet', assistant:'VZGplattform Assistent', evidence:'Erkannte Fakten', page:'Seite', original:'Deutscher Entwurf', translation:'Übersetzung & Erklärung', approve:'Prüfen und freigeben', neverSend:'Wird niemals automatisch versendet.', question:'Geht es um eine Frage zur Höhe der Nachzahlung oder möchten Sie der Hausverwaltung widersprechen?', check:'Nachzahlung prüfen', objection:'Widerspruch formulieren', response:'Antwort an die Hausverwaltung', data:'Ihre Daten bleiben geschützt', secure:'Sicher kommunizieren', control:'Sie behalten jederzeit die Kontrolle. Kein Schreiben wird ohne Ihre Freigabe versendet.', date:'', intro:'Beginnen Sie mit einem Dokument oder erzählen Sie uns, was passiert ist.', nav:['Übersicht','Meine Vorgänge','Dokumente','Entwürfe'], more:'Weitere Bereiche', templates:'Vorlagen', help:'Hilfe & Kontakt', helpButton:'Hilfe', doc:'Dokument', understand:'Verstehen', create:'Antwort erstellen', facts:[], explanation:'', sampleTitle:'', sampleText:'' },
  bg: { greeting:'Добро утро, ', subtitle:'С какво можем да помогнем днес?', uploadTitle:'Качете документ или въпрос', uploadText:'Поставете PDF, изображение или текст тук', browse:'Изберете файл', supported:'PDF, JPG, PNG · Макс. 10 MB', recent:'Последно редактирани', allCases:'Всички случаи', newCase:'Нов случай', clarify:'Нужен е отговор', draft:'Черновата е готова', processing:'Обработва се', assistant:'VZGplattform асистент', evidence:'Разпознати факти', page:'Страница', original:'Немска чернова', translation:'Превод и обяснение', approve:'Провери и одобри', neverSend:'Никога не се изпраща автоматично.', question:'Въпросът е за размера на доплащането или желаете възражение до управата?', check:'Провери доплащането', objection:'Формулирай възражение', response:'Отговор до управата', data:'Вашите данни са защитени', secure:'Сигурна комуникация', control:'Вие винаги запазвате контрола. Нищо не се изпраща без одобрение.', date:'', intro:'Започнете с документ или опишете какво се е случило.', nav:['Общ преглед','Моите случаи','Документи','Чернови'], more:'Други раздели', templates:'Шаблони', help:'Помощ и контакт', helpButton:'Помощ', doc:'Документ', understand:'Разбиране', create:'Създаване на отговор', facts:[], explanation:'', sampleTitle:'', sampleText:'' },
  ru: { greeting:'Доброе утро, ', subtitle:'Чем мы можем помочь сегодня?', uploadTitle:'Загрузите документ или вопрос', uploadText:'Перетащите сюда PDF, изображение или текст', browse:'Выбрать файл', supported:'PDF, JPG, PNG · Макс. 10 МБ', recent:'Недавно изменённые', allCases:'Все дела', newCase:'Новое дело', clarify:'Нужен ответ', draft:'Черновик готов', processing:'Обрабатывается', assistant:'Ассистент VZGplattform', evidence:'Распознанные факты', page:'Страница', original:'Немецкий черновик', translation:'Перевод и объяснение', approve:'Проверить и одобрить', neverSend:'Никогда не отправляется автоматически.', question:'Вопрос касается суммы доплаты или вы хотите составить возражение?', check:'Проверить доплату', objection:'Составить возражение', response:'Ответ управляющей компании', data:'Ваши данные защищены', secure:'Безопасная коммуникация', control:'Вы всегда сохраняете контроль. Письмо не отправляется без вашего одобрения.', date:'', intro:'Начните с документа или расскажите, что произошло.', nav:['Обзор','Мои дела','Документы','Черновики'], more:'Другие разделы', templates:'Шаблоны', help:'Помощь и контакты', helpButton:'Помощь', doc:'Документ', understand:'Понимание', create:'Создать ответ', facts:[], explanation:'', sampleTitle:'', sampleText:'' },
  pl: { greeting:'Dzień dobry, ', subtitle:'W czym możemy dziś pomóc?', uploadTitle:'Prześlij dokument lub pytanie', uploadText:'Upuść tutaj PDF, obraz lub tekst', browse:'Wybierz plik', supported:'PDF, JPG, PNG · Maks. 10 MB', recent:'Ostatnio edytowane', allCases:'Wszystkie sprawy', newCase:'Nowa sprawa', clarify:'Potrzebna odpowiedź', draft:'Projekt gotowy', processing:'Przetwarzanie', assistant:'Asystent VZGplattform', evidence:'Rozpoznane fakty', page:'Strona', original:'Niemiecki projekt', translation:'Tłumaczenie i wyjaśnienie', approve:'Sprawdź i zatwierdź', neverSend:'Nigdy nie jest wysyłany automatycznie.', question:'Czy chodzi o wysokość dopłaty, czy chcesz przygotować sprzeciw?', check:'Sprawdź dopłatę', objection:'Przygotuj sprzeciw', response:'Odpowiedź do administracji', data:'Twoje dane są chronione', secure:'Bezpieczna komunikacja', control:'Zawsze zachowujesz kontrolę. Żadne pismo nie zostanie wysłane bez zgody.', date:'', intro:'Zacznij od dokumentu lub opisz, co się wydarzyło.', nav:['Przegląd','Moje sprawy','Dokumenty','Projekty'], more:'Więcej sekcji', templates:'Szablony', help:'Pomoc i kontakt', helpButton:'Pomoc', doc:'Dokument', understand:'Zrozumienie', create:'Utwórz odpowiedź', facts:[], explanation:'', sampleTitle:'', sampleText:'' },
  sr: { greeting:'Добро јутро, ', subtitle:'Како можемо данас да помогнемо?', uploadTitle:'Отпремите документ или питање', uploadText:'Овде додајте PDF, слику или текст', browse:'Изаберите датотеку', supported:'PDF, JPG, PNG · Макс. 10 MB', recent:'Недавно обрађено', allCases:'Сви предмети', newCase:'Нови предмет', clarify:'Потребан је одговор', draft:'Нацрт је спреман', processing:'Обрада у току', assistant:'VZGplattform асистент', evidence:'Препознате чињенице', page:'Страна', original:'Немачки нацрт', translation:'Превод и објашњење', approve:'Провери и одобри', neverSend:'Никада се не шаље аутоматски.', question:'Да ли се питање односи на доплату или желите да саставимо приговор?', check:'Провери доплату', objection:'Састави приговор', response:'Одговор управи зграде', data:'Ваши подаци су заштићени', secure:'Безбедна комуникација', control:'Ви увек задржавате контролу. Писмо се не шаље без вашег одобрења.', date:'', intro:'Почните документом или опишите шта се догодило.', nav:['Преглед','Моји предмети','Документи','Нацрти'], more:'Остале области', templates:'Шаблони', help:'Помоћ и контакт', helpButton:'Помоћ', doc:'Документ', understand:'Разумевање', create:'Направи одговор', facts:[], explanation:'', sampleTitle:'', sampleText:'' },
  ro: { greeting:'Bună dimineața, ', subtitle:'Cu ce vă putem ajuta astăzi?', uploadTitle:'Încărcați un document sau o întrebare', uploadText:'Plasați aici un PDF, o imagine sau un text', browse:'Alegeți fișierul', supported:'PDF, JPG, PNG · Max. 10 MB', recent:'Modificate recent', allCases:'Toate cazurile', newCase:'Caz nou', clarify:'Este necesar un răspuns', draft:'Proiect gata', processing:'Se procesează', assistant:'Asistentul VZGplattform', evidence:'Fapte identificate', page:'Pagina', original:'Proiect în germană', translation:'Traducere și explicație', approve:'Verificați și aprobați', neverSend:'Nu este trimis niciodată automat.', question:'Este vorba despre suma suplimentară sau doriți să formulați o contestație?', check:'Verificați suma', objection:'Formulați o contestație', response:'Răspuns către administrație', data:'Datele dvs. sunt protejate', secure:'Comunicați în siguranță', control:'Păstrați mereu controlul. Nicio scrisoare nu este trimisă fără aprobare.', date:'', intro:'Începeți cu un document sau descrieți ce s-a întâmplat.', nav:['Prezentare','Cazurile mele','Documente','Proiecte'], more:'Alte secțiuni', templates:'Modele', help:'Ajutor și contact', helpButton:'Ajutor', doc:'Document', understand:'Înțelegere', create:'Creați răspunsul', facts:[], explanation:'', sampleTitle:'', sampleText:'' },
}

function getLocale(pathname: string): Locale { const value = pathname.split('/')[1] as Locale; return locales.includes(value) ? value : 'de' }

export default function Page() {
  const pathname = usePathname(); const router = useRouter(); const locale = getLocale(pathname); const t = copy[locale]; const supabase = createClient()
  const [uploaded, setUploaded] = useState(false); const [stage, setStage] = useState<'empty'|'clarify'|'draft'>('empty'); const [selectedFile, setSelectedFile] = useState<File | null>(null); const [mobileNav, setMobileNav] = useState(false)
  const changeLocale = (next: Locale) => router.push(`/${next}/office`)
  return <div lang={locale} className="min-h-screen bg-background text-foreground">
    <header className="flex h-16 items-center justify-between border-b bg-card px-4 lg:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 hover:bg-muted lg:hidden" onClick={() => setMobileNav(!mobileNav)} aria-label={t.helpButton}><Menu /></button><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-5" /></div><div><div className="font-semibold tracking-tight">VZGplattform</div><div className="hidden text-[11px] text-muted-foreground sm:block">Kommunikationsassistent</div></div></div><div className="flex items-center gap-2 sm:gap-5"><div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><ShieldCheck className="size-4 text-primary" /> {t.data}</div><div className="flex items-center gap-1 rounded-lg border bg-background px-2 py-1.5"><Globe2 className="size-4 text-muted-foreground" /><select aria-label={t.language ?? 'Language'} value={locale} onChange={e => changeLocale(e.target.value as Locale)} className="bg-transparent text-xs font-medium outline-none">{locales.map(item => <option key={item} value={item}>{localeNames[item]}</option>)}</select><ChevronDown className="size-3 text-muted-foreground" /></div><button className="flex size-9 items-center justify-center rounded-full bg-secondary text-sm font-semibold" aria-label="Profil">M</button></div></header>
    <div className="flex"><aside className={`${mobileNav ? 'block' : 'hidden'} absolute z-10 min-h-[calc(100vh-4rem)] w-64 border-r bg-card p-4 lg:static lg:block`}><button onClick={() => { setStage('empty'); setUploaded(false) }} className="mb-6 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground shadow-sm transition hover:opacity-90"><Plus className="size-4" /> {t.newCase}</button><nav className="flex flex-col gap-1">{t.nav.map((label:string, i:number) => { const icons=[LayoutDashboard,Inbox,FileText,FileCheck2]; const Icon=icons[i]; return <button key={label} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm text-muted-foreground transition hover:bg-muted hover:text-foreground"><Icon className="size-4" />{label}</button> })}</nav><div className="my-6 h-px bg-border" /><div className="px-3 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{t.more}</div><nav className="mt-2 flex flex-col gap-1"><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><BookOpen className="size-4" /> {t.templates}</button><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><LifeBuoy className="size-4" /> {t.help}</button></nav><div className="mt-8 hidden rounded-xl bg-muted p-3 lg:block"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><ShieldCheck className="size-4 text-primary" /> {t.secure}</div><p className="text-[11px] leading-relaxed text-muted-foreground">{t.control}</p></div></aside>
      <main className="w-full max-w-6xl px-4 py-8 sm:px-8 lg:px-12"><div className="mb-6 flex items-start gap-3 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm"><WifiOff className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-semibold">{supabase ? (t.previewTitle ?? 'Preview Mode') : authCopy[locale].setup}</p><p className="mt-1 text-muted-foreground">{supabase ? (t.previewText ?? '') : authCopy[locale].setupText}</p></div></div><div className="mb-8"><p className="mb-1 text-sm text-muted-foreground">{t.date}</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{t.greeting}</h1><p className="mt-1 text-muted-foreground">{t.subtitle}</p></div>
        <section className="mb-10 rounded-2xl border bg-card p-5 shadow-sm sm:p-8"><div className="mb-6 flex items-start justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-primary"><MessageCircle className="size-4" /> {t.assistant}</div><h2 className="text-xl font-semibold">{t.uploadTitle}</h2><p className="mt-1 text-sm text-muted-foreground">{t.intro}</p></div><button className="hidden rounded-lg p-2 text-muted-foreground hover:bg-muted sm:block" aria-label="More"><MoreHorizontal className="size-5" /></button></div><div className={`rounded-xl border-2 border-dashed p-6 text-center transition sm:p-10 ${uploaded ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/50 hover:bg-muted/40'}`}><div className="mx-auto mb-4 flex size-12 items-center justify-center rounded-full bg-secondary text-primary">{uploaded ? <Check className="size-6" /> : <Upload className="size-6" />}</div><p className="font-medium">{uploaded && selectedFile ? selectedFile.name : t.uploadText}</p><p className="mt-1 text-xs text-muted-foreground">{uploaded && selectedFile ? `${(selectedFile.size / 1024 / 1024).toFixed(1)} MB · ${selectedFile.type || 'Datei'}` : t.supported}</p>{!uploaded && <label className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-lg border bg-background px-4 py-2 text-sm font-semibold shadow-sm hover:bg-muted"><Paperclip className="size-4" /> {t.browse}<input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => { const file = event.target.files?.[0]; if (file) { setSelectedFile(file); setUploaded(true); setStage('clarify') } }} /></label>}</div><div className="mt-7 flex items-center gap-2"><Step n="1" label={t.doc} active={true} /><div className="h-px flex-1 bg-border" /><Step n="2" label={t.understand} active={stage !== 'empty'} /><div className="h-px flex-1 bg-border" /><Step n="3" label={t.create} active={stage === 'draft'} /></div>{stage === 'clarify' && <div className="mt-6 rounded-xl border border-primary/30 bg-primary/5 p-4"><div className="flex gap-3"><CircleHelp className="mt-0.5 size-5 shrink-0 text-primary" /><div className="flex-1"><p className="font-semibold">{t.clarify}</p><p className="mt-1 text-sm text-muted-foreground">{t.question}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setStage('draft')} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">{t.check}</button><button onClick={() => setStage('draft')} className="rounded-lg border bg-background px-3 py-2 text-xs font-semibold">{t.objection}</button></div></div></div></div>}</section>
        {stage === 'draft' && <DraftPanel t={t} locale={locale} />}
        <CaseWorkspace locale={locale} file={selectedFile ?? undefined} />
        <section className="mt-8 rounded-xl border bg-card p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><Languages className="size-4 text-primary" /> {t.language ?? 'Sprachen'}</div><div className="flex flex-wrap gap-2">{locales.map(item => <button key={item} onClick={() => changeLocale(item)} className={`rounded-full border px-3 py-1.5 text-xs ${item === locale ? 'border-primary bg-primary/10 font-semibold text-primary' : 'text-muted-foreground hover:bg-muted'}`}>{localeNames[item]}</button>)}</div></section>
      </main></div><div className="fixed bottom-4 right-4"><button className="flex items-center gap-2 rounded-full border bg-card px-4 py-3 text-sm font-medium shadow-lg hover:bg-muted"><CircleHelp className="size-4 text-primary" /> {t.helpButton}</button></div>
  </div>
}

function Step({ n, label, active }: { n:string; label:string; active:boolean }) { return <div className={`flex shrink-0 items-center gap-2 text-xs font-medium ${active ? 'text-primary' : 'text-muted-foreground'}`}><span className={`flex size-6 items-center justify-center rounded-full text-[11px] ${active ? 'bg-primary text-primary-foreground' : 'bg-muted'}`}>{n}</span><span className="hidden sm:inline">{label}</span></div> }
function DraftPanel({ t }: { t:any; locale:Locale }) { return <section className="mb-10 rounded-2xl border bg-card shadow-sm"><div className="p-5"><div className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-primary"><FileCheck2 className="size-4" /> {t.draft}</div><h2 className="text-xl font-semibold">{t.response}</h2><p className="mt-4 rounded-lg border border-primary/20 bg-primary/5 p-4 text-sm text-muted-foreground">{t.missingInformation ?? ''}</p><p className="mt-3 text-sm text-muted-foreground">{t.neverSend}</p></div></section> }
