import type { Locale } from './supabase/database'

export const authCopy: Record<Locale, { login: string; signup: string; forgot: string; reset: string; email: string; password: string; displayName: string; submitLogin: string; submitSignup: string; submitForgot: string; submitReset: string; noAccount: string; hasAccount: string; forgotLink: string; backLogin: string; signOut: string; setup: string; setupText: string; success: string; resetSent: string; error: string }> = {
  bg: { login:'Вход', signup:'Регистрация', forgot:'Забравена парола', reset:'Нова парола', email:'Имейл', password:'Парола', displayName:'Име за показване', submitLogin:'Вход', submitSignup:'Създай профил', submitForgot:'Изпрати линк', submitReset:'Запази паролата', noAccount:'Нямате профил?', hasAccount:'Вече имате профил?', forgotLink:'Забравена парола?', backLogin:'Обратно към вход', signOut:'Изход', setup:'Supabase не е конфигуриран', setupText:'Добавете environment variables, за да активирате автентикацията.', success:'Провери имейла си за потвърждение.', resetSent:'Изпратихме линк за възстановяване.', error:'Възникна грешка. Опитайте отново.' },
  de: { login:'Anmelden', signup:'Registrieren', forgot:'Passwort vergessen', reset:'Neues Passwort', email:'E-Mail', password:'Passwort', displayName:'Anzeigename', submitLogin:'Anmelden', submitSignup:'Profil erstellen', submitForgot:'Link senden', submitReset:'Passwort speichern', noAccount:'Noch kein Profil?', hasAccount:'Schon registriert?', forgotLink:'Passwort vergessen?', backLogin:'Zurück zur Anmeldung', signOut:'Abmelden', setup:'Supabase ist nicht konfiguriert', setupText:'Environment-Variablen müssen eingerichtet werden.', success:'Bitte bestätigen Sie Ihre E-Mail-Adresse.', resetSent:'Ein Wiederherstellungslink wurde gesendet.', error:'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.' },
  ru: { login:'Войти', signup:'Регистрация', forgot:'Забыли пароль', reset:'Новый пароль', email:'Электронная почта', password:'Пароль', displayName:'Отображаемое имя', submitLogin:'Войти', submitSignup:'Создать профиль', submitForgot:'Отправить ссылку', submitReset:'Сохранить пароль', noAccount:'Нет профиля?', hasAccount:'Уже зарегистрированы?', forgotLink:'Забыли пароль?', backLogin:'Вернуться ко входу', signOut:'Выйти', setup:'Supabase не настроен', setupText:'Настройте переменные окружения.', success:'Проверьте почту для подтверждения.', resetSent:'Ссылка восстановления отправлена.', error:'Произошла ошибка. Попробуйте снова.' },
  pl: { login:'Logowanie', signup:'Rejestracja', forgot:'Nie pamiętam hasła', reset:'Nowe hasło', email:'E-mail', password:'Hasło', displayName:'Nazwa wyświetlana', submitLogin:'Zaloguj się', submitSignup:'Utwórz profil', submitForgot:'Wyślij link', submitReset:'Zapisz hasło', noAccount:'Nie masz profilu?', hasAccount:'Masz już konto?', forgotLink:'Nie pamiętasz hasła?', backLogin:'Wróć do logowania', signOut:'Wyloguj się', setup:'Supabase nie jest skonfigurowany', setupText:'Skonfiguruj zmienne środowiskowe.', success:'Sprawdź e-mail, aby potwierdzić konto.', resetSent:'Wysłano link odzyskiwania.', error:'Wystąpił błąd. Spróbuj ponownie.' },
  sr: { login:'Пријава', signup:'Регистрација', forgot:'Заборављена лозинка', reset:'Нова лозинка', email:'Имејл', password:'Лозинка', displayName:'Име за приказ', submitLogin:'Пријави се', submitSignup:'Направи профил', submitForgot:'Пошаљи линк', submitReset:'Сачувај лозинку', noAccount:'Немате профил?', hasAccount:'Већ имате профил?', forgotLink:'Заборавили сте лозинку?', backLogin:'Назад на пријаву', signOut:'Одјава', setup:'Supabase није подешен', setupText:'Подесите environment variables.', success:'Проверите имејл за потврду.', resetSent:'Послат је линк за опоравак.', error:'Дошло је до грешке. Покушајте поново.' },
  ro: { login:'Autentificare', signup:'Înregistrare', forgot:'Parolă uitată', reset:'Parolă nouă', email:'E-mail', password:'Parolă', displayName:'Nume afișat', submitLogin:'Autentificare', submitSignup:'Creează profil', submitForgot:'Trimite linkul', submitReset:'Salvează parola', noAccount:'Nu aveți profil?', hasAccount:'Aveți deja un cont?', forgotLink:'Ați uitat parola?', backLogin:'Înapoi la autentificare', signOut:'Deconectare', setup:'Supabase nu este configurat', setupText:'Configurați variabilele de mediu.', success:'Verificați e-mailul pentru confirmare.', resetSent:'Am trimis un link de recuperare.', error:'A apărut o eroare. Încercați din nou.' },
}
