import type { CaseStatus, Locale } from './supabase/database'

const labels: Record<Locale, Record<CaseStatus, string>> = {
  bg: { NEW:'Нов', UPLOADED:'Качен', EXTRACTING:'Обработва се', NEEDS_INFO:'Нужна информация', DRAFTING:'Чернова', NEEDS_CONFIRMATION:'Чака потвърждение', APPROVED:'Одобрен', EXPORTED:'Експортиран', SENT:'Изпратен', WAITING_REPLY:'Чака отговор', ACTION_REQUIRED:'Нужно действие', CLOSED:'Приключен', FAILED_RETRYABLE:'Повторен опит', FAILED_FINAL:'Неуспешен', HUMAN_REVIEW:'Човешка проверка' },
  de: { NEW:'Neu', UPLOADED:'Hochgeladen', EXTRACTING:'Wird verarbeitet', NEEDS_INFO:'Information nötig', DRAFTING:'Entwurf', NEEDS_CONFIRMATION:'Bestätigung nötig', APPROVED:'Freigegeben', EXPORTED:'Exportiert', SENT:'Gesendet', WAITING_REPLY:'Wartet auf Antwort', ACTION_REQUIRED:'Aktion nötig', CLOSED:'Abgeschlossen', FAILED_RETRYABLE:'Wiederholung', FAILED_FINAL:'Fehlgeschlagen', HUMAN_REVIEW:'Manuelle Prüfung' },
  ru: { NEW:'Новое', UPLOADED:'Загружено', EXTRACTING:'Обрабатывается', NEEDS_INFO:'Нужна информация', DRAFTING:'Черновик', NEEDS_CONFIRMATION:'Нужно подтверждение', APPROVED:'Одобрено', EXPORTED:'Экспортировано', SENT:'Отправлено', WAITING_REPLY:'Ожидает ответа', ACTION_REQUIRED:'Нужно действие', CLOSED:'Закрыто', FAILED_RETRYABLE:'Повторить', FAILED_FINAL:'Ошибка', HUMAN_REVIEW:'Проверка человеком' },
  pl: { NEW:'Nowa', UPLOADED:'Przesłana', EXTRACTING:'Przetwarzanie', NEEDS_INFO:'Potrzebne informacje', DRAFTING:'Projekt', NEEDS_CONFIRMATION:'Potrzebne potwierdzenie', APPROVED:'Zatwierdzona', EXPORTED:'Wyeksportowana', SENT:'Wysłana', WAITING_REPLY:'Oczekuje na odpowiedź', ACTION_REQUIRED:'Wymaga działania', CLOSED:'Zamknięta', FAILED_RETRYABLE:'Do ponowienia', FAILED_FINAL:'Nieudana', HUMAN_REVIEW:'Kontrola człowieka' },
  sr: { NEW:'Ново', UPLOADED:'Отпремљено', EXTRACTING:'Обрада', NEEDS_INFO:'Потребне информације', DRAFTING:'Нацрт', NEEDS_CONFIRMATION:'Потребна потврда', APPROVED:'Одобрено', EXPORTED:'Извезено', SENT:'Послато', WAITING_REPLY:'Чека одговор', ACTION_REQUIRED:'Потребна радња', CLOSED:'Затворено', FAILED_RETRYABLE:'Поновити', FAILED_FINAL:'Неуспешно', HUMAN_REVIEW:'Људска провера' },
  ro: { NEW:'Nou', UPLOADED:'Încărcat', EXTRACTING:'Se procesează', NEEDS_INFO:'Informații necesare', DRAFTING:'Proiect', NEEDS_CONFIRMATION:'Necesită confirmare', APPROVED:'Aprobat', EXPORTED:'Exportat', SENT:'Trimis', WAITING_REPLY:'Așteaptă răspuns', ACTION_REQUIRED:'Necesită acțiune', CLOSED:'Închis', FAILED_RETRYABLE:'De reîncercat', FAILED_FINAL:'Eșuat', HUMAN_REVIEW:'Verificare umană' },
}

export function caseStatusLabel(locale: Locale, status: CaseStatus) { return labels[locale][status] }
