import type { Locale } from './supabase/database'
export const detailCopy: Record<Locale, { back:string; timeline:string; documents:string; facts:string; drafts:string; messages:string; noData:string; archive:string; archived:string; export:string; recipient:string; evidence:string; page:string; settings:string; interfaceLanguage:string; conversationLanguage:string; outputLanguage:string; displayName:string; privacy:string; save:string; saved:string }> = {
 bg:{back:'Назад към таблото',timeline:'Хронология',documents:'Документи',facts:'Потвърдени факти',drafts:'Чернови',messages:'Съобщения',noData:'Няма данни.',archive:'Архивирай',archived:'Архивиран',export:'Изтегли',recipient:'Получател',evidence:'Доказателство',page:'Страница',settings:'Настройки',interfaceLanguage:'Език на интерфейса',conversationLanguage:'Език на разговора',outputLanguage:'Език на изхода',displayName:'Име за показване',privacy:'Данните са частни и достъпни само за вашия профил.',save:'Запази',saved:'Запазено.'},
 de:{back:'Zurück zum Dashboard',timeline:'Zeitachse',documents:'Dokumente',facts:'Bestätigte Fakten',drafts:'Entwürfe',messages:'Nachrichten',noData:'Keine Daten.',archive:'Archivieren',archived:'Archiviert',export:'Herunterladen',recipient:'Empfänger',evidence:'Nachweis',page:'Seite',settings:'Einstellungen',interfaceLanguage:'Sprache der Oberfläche',conversationLanguage:'Gesprächssprache',outputLanguage:'Ausgabesprache',displayName:'Anzeigename',privacy:'Ihre Daten sind privat und nur für Ihr Profil zugänglich.',save:'Speichern',saved:'Gespeichert.'},
 ru:{back:'Назад к панели',timeline:'Хронология',documents:'Документы',facts:'Подтверждённые факты',drafts:'Черновики',messages:'Сообщения',noData:'Нет данных.',archive:'Архивировать',archived:'Архивировано',export:'Скачать',recipient:'Получатель',evidence:'Доказательство',page:'Страница',settings:'Настройки',interfaceLanguage:'Язык интерфейса',conversationLanguage:'Язык разговора',outputLanguage:'Язык результата',displayName:'Имя для отображения',privacy:'Данные приватны и доступны только вашему профилю.',save:'Сохранить',saved:'Сохранено.'},
 pl:{back:'Powrót do panelu',timeline:'Oś czasu',documents:'Dokumenty',facts:'Potwierdzone fakty',drafts:'Projekty',messages:'Wiadomości',noData:'Brak danych.',archive:'Archiwizuj',archived:'Zarchiwizowano',export:'Pobierz',recipient:'Odbiorca',evidence:'Dowód',page:'Strona',settings:'Ustawienia',interfaceLanguage:'Język interfejsu',conversationLanguage:'Język rozmowy',outputLanguage:'Język wyniku',displayName:'Nazwa wyświetlana',privacy:'Dane są prywatne i dostępne tylko dla Twojego profilu.',save:'Zapisz',saved:'Zapisano.'},
 sr:{back:'Назад на контролну таблу',timeline:'Временска линија',documents:'Документи',facts:'Потврђене чињенице',drafts:'Нацрти',messages:'Поруке',noData:'Нема података.',archive:'Архивирај',archived:'Архивирано',export:'Преузми',recipient:'Прималац',evidence:'Доказ',page:'Страница',settings:'Подешавања',interfaceLanguage:'Језик интерфејса',conversationLanguage:'Језик разговора',outputLanguage:'Језик резултата',displayName:'Име за приказ',privacy:'Подаци су приватни и доступни само вашем профилу.',save:'Сачувај',saved:'Сачувано.'},
 ro:{back:'Înapoi la panou',timeline:'Cronologie',documents:'Documente',facts:'Fapte confirmate',drafts:'Proiecte',messages:'Mesaje',noData:'Nu există date.',archive:'Arhivează',archived:'Arhivat',export:'Descarcă',recipient:'Destinatar',evidence:'Dovadă',page:'Pagină',settings:'Setări',interfaceLanguage:'Limba interfeței',conversationLanguage:'Limba conversației',outputLanguage:'Limba rezultatului',displayName:'Nume afișat',privacy:'Datele sunt private și accesibile doar profilului dvs.',save:'Salvează',saved:'Salvat.'},
}
