/**
 * P9 — template loading and PDF writer boundary.
 *
 * The engine needs two capabilities from outside itself: reading a template's
 * interactive fields, and writing values into a copy of it. Both are behind this
 * boundary so the engine stays pure and testable.
 *
 * Reading uses `pdfjs-dist`; writing uses `pdf-lib`, added with the owner's
 * explicit approval. Two template shapes are supported, and the engine keeps both
 * paths: an official template that exposes real AcroForm fields is filled by field
 * name (`fill.ts`), while the currently verified FMS templates are static
 * printable forms and are filled by hash-bound overlay (`overlay-map.ts`,
 * `overlay-fill.ts`).
 */

import { readFile } from "node:fs/promises"
import { resolve } from "node:path"
import { PDFDocument, StandardFonts } from "pdf-lib"
import type { PdfFieldAssignment } from "./fill"
import type { OverlayPlan } from "./overlay-fill"
import type { StaticTemplateMapping } from "./overlay-map"
import { writeOverlay, type OverlayWriteResult } from "./overlay-writer"
import { isWinAnsiRepresentable } from "./encoding"

/**
 * A writer is now installed: `pdf-lib`, approved by the owner for the Official
 * PDF Form Engine. It is the only PDF writer in the project by design — a second
 * one would fragment how official forms are produced.
 */
export const PDF_WRITER_STATUS = "pdf-lib" as const

export type PdfWriterAvailability = { available: true; engine: "pdf-lib" }

export function writerAvailability(): PdfWriterAvailability {
  return { available: true, engine: "pdf-lib" }
}

/**
 * Measures drawn text with the same face the writer uses.
 *
 * The planner needs real widths to refuse overflow, so this embeds Helvetica in a
 * throwaway document and asks pdf-lib. Using the writer's own metrics means the
 * overflow check cannot disagree with what is actually drawn.
 */
export async function createTextMeasurer(): Promise<(text: string, size: number) => number> {
  const probe = await PDFDocument.create()
  const font = await probe.embedFont(StandardFonts.Helvetica)
  return (text, size) => font.widthOfTextAtSize(text, size)
}

export type TemplateBytes = { ok: true; bytes: Uint8Array } | { ok: false; detail: string }

/** Reads a registered template from the repository. */
export async function readTemplateBytes(path: string): Promise<TemplateBytes> {
  try {
    const loaded = await readFile(resolve(process.cwd(), path))
    return { ok: true, bytes: new Uint8Array(loaded) }
  } catch (error) {
    return { ok: false, detail: error instanceof Error ? error.message : "read_failed" }
  }
}

export type FieldReader = () => Promise<readonly string[] | null>

/**
 * Reads interactive field names from PDF bytes using the installed reader.
 *
 * The reader is imported lazily so this module stays importable in contexts
 * (tests, edge runtime) that should not pull in the PDF reader. A reader failure
 * returns `null`, which the capability detector treats as "no exposed fields" —
 * the conservative interpretation that leads to a refusal rather than a
 * guess.
 */
export async function readAcroFormFieldNames(bytes: Uint8Array): Promise<readonly string[] | null> {
  try {
    const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs")
    const document = await pdfjs.getDocument({
      data: bytes,
      useSystemFonts: false,
    }).promise
    try {
      const fields = await document.getFieldObjects()
      if (!fields) return null
      const names = Array.from(fields.keys())
      return names
    } finally {
      await document.cleanup()
    }
  } catch {
    return null
  }
}

export type GeneratedPdf =
  | { ok: true; bytes: Uint8Array; filledCount: number }
  | { ok: false; code: "write_failed" | "winansi_unsupported"; detail: string }

/**
 * Produces the filled PDF from a planned overlay.
 *
 * This is the single call site that writes a document. It delegates to the
 * overlay writer, which reads only the template bytes and the plan — so the
 * decision about *which* values belong on the form stays in `planOverlayFill`,
 * where it is covered by tests, and never moves into the writer.
 */
export async function generateOverlayPdf(input: {
  templateBytes: Uint8Array
  mapping: StaticTemplateMapping
  plan: Extract<OverlayPlan, { ok: true }>
  shade?: boolean
}): Promise<GeneratedPdf> {
  const written: OverlayWriteResult = await writeOverlay({
    templateBytes: input.templateBytes,
    mapping: input.mapping,
    plan: input.plan,
    shade: input.shade,
  })
  if (!written.ok) return written
  return { ok: true, bytes: written.bytes, filledCount: written.filledCount }
}

/**
 * Path A — fills real AcroForm fields by name and optionally flattens.
 *
 * Used only when a template genuinely exposes an interactive form. `flatten`
 * makes the values part of the page content so the document cannot be edited back
 * to an empty form after approval, which matters because approval is bound to the
 * generated bytes.
 */
export async function generateAcroFormPdf(input: {
  templateBytes: Uint8Array
  assignments: readonly PdfFieldAssignment[]
  flatten: boolean
}): Promise<GeneratedPdf> {
  try {
    const document = await PDFDocument.load(input.templateBytes)
    const form = document.getForm()
    let applied = 0

    for (const assignment of input.assignments) {
      const text = String(assignment.value)
      if (!isWinAnsiRepresentable(text)) {
        return { ok: false, code: "winansi_unsupported", detail: assignment.fieldName }
      }
      if (assignment.kind === "text") {
        const field = form.getTextField(assignment.fieldName)
        field.setText(text)
        applied += 1
        continue
      }
      // Underlying form primitives are untyped in pdf-lib; the assignment's kind
      // was decided by `planPdfFill`, which only emits these shapes for a field it
      // verified exists.
      const field = document.getForm().getField(assignment.fieldName)
      const mutable = field as unknown as { check?: () => void; select?: (value: string) => void }
      if (assignment.kind === "checkbox") {
        mutable.check?.()
      } else {
        mutable.select?.(text)
      }
      applied += 1
    }

    if (input.flatten) form.flatten()
    const bytes = await document.save()
    return { ok: true, bytes, filledCount: applied }
  } catch (error) {
    return {
      ok: false,
      code: "write_failed",
      detail: error instanceof Error ? error.message : "write_failed",
    }
  }
}